[general]
# Import theme rose-pine
# https://github.com/rose-pine/alacritty
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.9
padding.x = 10
padding.y = 10
#decorations_theme_variant = "Light" # "Dark"
startup_mode = "Maximized"

# Fonts
# https://wiki.archlinux.org/title/Alacritty#Font
[font]
normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
size = 14

# Spawn new instance in same directory
# https://wiki.archlinux.org/title/Alacritty#Spawn_new_instance_in_same_directory
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]


# https://alacritty.org/config-alacritty.html#terminal
[terminal]
shell = "zellij"
